teste = input("Digite algo: ")

print('Tipo: ', type(teste))
print('Alfanumérico: ', teste.isalnum())
print('Numérico: ', teste.isnumeric())
print('Alfabético: ', teste.isalpha())
print('ASCII: ', teste.isascii())
print('Dígito: ', teste.isdigit())
print('Espaço: ', teste.isspace())
print('Decimal: ', teste.isdecimal())
print('Identificador: ', teste.isidentifier())
print('Minúscula: ', teste.islower())
print('Maiúscula: ', teste.isupper())
print('Título: ', teste.istitle())
